trigger:
  branches:
    include:
      - master
  tags:
    include:
      - "*"

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
      python.version: '3.x'

pool:
  vmImage: $(imageName)
variables:
  tag: '$(Build.BuildId)'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- task: Docker@2
  # condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'aaronwolen/azure-ci-test'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.SourceBranchName)
      latest
