trigger:
  branches:
    include:
      - master
  tags:
    include:
      - "*"

jobs:
- job: Setup

  strategy:
    matrix:
      linux18:
        imageName: 'ubuntu-18.04'
        python.version: '3.x'
      linux16:
        imageName: 'ubuntu-16.04'
        python.version: '3.x'

  pool:
    vmImage: $(imageName)
  variables:
    tag: '$(Build.BuildId)'

  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'env | sort'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

- job: Images
  dependsOn: Setup
  condition: |
    or(
      eq(variables['build.sourceBranch'], 'refs/heads/master'),
      startsWith(variables['build.sourceBranch'], 'refs/tags')
    )

  strategy:
    matrix:
      image1:
        dockerfile: Dockerfile
        repository: aaronwolen/azure-ci-test
      image2:
        dockerfile: Dockerfile-sh
        repository: aaronwolen/azure-ci-test-2

  steps:
  - template: ci/build-images.yml
