trigger:
  branches:
    include:
      - master
  tags:
    include:
      - "*"

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
      python.version: '3.x'

pool:
  vmImage: $(imageName)
variables:
  tag: '$(Build.BuildId)'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'env | sort'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- task: Docker@2
  displayName: Docker image (latest)
  condition: or(eq(variables['build.sourceBranch'], 'refs/heads/master'), startsWith(variables['build.sourceBranch'], 'refs/tags'))
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'aaronwolen/azure-ci-test'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: latest

- task: Docker@2
  displayName: Docker image (tagged release)
  condition: startsWith(variables['build.sourceBranch'], 'refs/tags')
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'aaronwolen/azure-ci-test'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: '.'
    tags: $(Build.SourceBranchName)
